### ISSUE TITLE
STM Morpho Header子板购买

### ISSUE THREAD

**Issue by czxlesh** [yplam/LoraRangingTest#1]
您好，不知道从哪里可以购买到您项目图片里面的STM Morpho Header子板？我想重现您展示的系统来测量收发设备之间的距离，但是无法购买到图片中的STM Morpho Header子板。想请教您从哪里可以购买到该子板。谢谢您。

**Comment by yplam** [comment]
你好，pcb是自己做的，模块网上可以买到

**Comment by czxlesh** [comment]
您好，由于我们是在校学生，不太熟悉电路设计和制作，想在近期急用这一模块，请问您是否方便提供一下电路图呢？非常感谢您的回复和帮助！

**Comment by yplam** [comment]
抱歉只有png格式的电路图

**Comment by czxlesh** [comment]
嗯嗯，那请问您方便提供给我们学习一下吗？非常感谢！
